Returns response error message when not successful
Was trying to run the example, but the ID for Ubuntu had changed, so it just failed without saying that the image was invalid. This gives the response error message.

Before:
```
Error: /Stage[main]/Main/Droplet[puppet-master-digitalocean]/ensure: change from absent to present failed: Failed to create droplet
```

After:
```
Error: Failed to create droplet: You specified an invalid image for Droplet creation.
Error: /Stage[main]/Main/Droplet[puppet-master-digitalocean]/ensure: change from absent to present failed: Failed to create droplet: You specified an invalid image for Droplet creation.
Notice: Finished catalog run in 1.13 seconds
```